# Generated by Django 2.2.12 on 2020-06-23 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
