# Generated by Django 2.2.12 on 2020-06-23 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_qualification_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='location_id',
            field=models.TextField(default=''),
        ),
    ]
