# Generated by Django 2.2.12 on 2020-06-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_remove_qualification_location_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='location_id',
            field=models.TextField(default=''),
        ),
    ]
