# Generated by Django 2.2.12 on 2020-06-25 13:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='date',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='date',
        ),
        migrations.AddField(
            model_name='experience',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='experience',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='qualification',
            name='date_end',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='qualification',
            name='date_start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
