# Generated by Django 2.2.12 on 2020-06-25 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0010_auto_20200625_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='duties',
        ),
        migrations.AlterField(
            model_name='experience',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='skill',
            name='heading',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='ExperienceDuties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty', models.TextField()),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cv.Experience')),
            ],
        ),
    ]
