# Generated by Django 2.2.12 on 2020-06-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0011_auto_20200625_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='duties',
            field=models.CharField(default='', max_length=100),
        ),
    ]
