# Generated by Django 2.2.12 on 2020-06-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0012_experience_duties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienceduties',
            name='experience',
        ),
        migrations.AlterField(
            model_name='experience',
            name='duties',
            field=models.TextField(),
        ),
    ]
